### ISSUE TITLE
There's no install.inf file

### ISSUE THREAD

**Issue by meymigrou** [ful1e5/apple_cursor#100]
I'm trying to install the cursors but there's no install.inf file. I downloaded them again and still no such file. Running the command "Start-Process install.inf -Verb Install" another user has suggested also didn't work for me, as it says:

```
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start-Process install.inf -Verb Install
```

How do I install them in Windows 11?

**Comment by ful1e5** [comment]
@meymigrou I'm currently working on the next release, which includes significant updates and changes. This will address your issue. Please await the upcoming release.

**Comment by ZenShouko** [comment]
I second this ^, waiting for either an install file or cur files so I can use it on my win11 machine:)
