### ISSUE TITLE
Error while trying to install cursors

### ISSUE THREAD

**Issue by mazzlabs** [ful1e5/apple_cursor#23]
## Description of the problem
An error happened while trying to install this cursor scheme on my machine.

## How has this issue affected you? What are you trying to accomplish?
I was trying to install the cursors. Here's a detailed list of what I did.

1. Installed the latest **Windows release** file [here](https://github.com/ful1e5/apple_cursor/releases).
2. Unzipped it using **WinRAR**.
3. Opened the unzipped folder, and right clicked on the `.inf` file in order to **install it**.
3. Got an **error** saying: 
`The INF file you selected does not support this method of installation.`
`The style of INF is different than what was requested.`

### Logs or Screenshots: (in french, sorry)
![image](https://user-images.githubusercontent.com/37367577/91419777-1a0a4900-e854-11ea-9546-52df91dc4b7e.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System | Windows 10 (x64/86) |

**Comment by ful1e5** [comment]
Try to install latest dev [build](https://github.com/ful1e5/apple_cursor/actions/runs/224913770) (Download the `macOS Big Sur.zip`  archive in **artifacts** section).
Ping me if this patch works for you 🤗.

**Comment by mazzlabs** [comment]
It worked! Thank you very much for taking the time to patch this 😉
