### ISSUE TITLE
Can't Install on Windows

### ISSUE THREAD

**Issue by artogahr** [ful1e5/apple_cursor#24]
## Description of the problem

Right clicking and selecting "Install" and granting required elevations gives out following error:
`The style of INF is different than what was requested.`
### Logs or Screenshots: (optional)
![image](https://user-images.githubusercontent.com/22445057/91633524-89696f80-e9f1-11ea-873c-38bf1069c9de.png)

### Your Environment

Windows 10 Pro Build 2004

**Comment by ful1e5** [comment]
Duplicate of #23 
New Packages are available soon(**[v1.0.3](https://github.com/ful1e5/apple_cursor/milestone/2)**) 😊

**Comment by artogahr** [comment]
Oh ok, good luck!
