### ISSUE TITLE
Cursor is not in expected position

### ISSUE THREAD

**Issue by iamr8** [ful1e5/apple_cursor#37]
## Description of the problem
In v1.1.0 default cursur is not in correct position. I mean top-left of the cursor should be sensitive to pointer position, but in picture as you see, It's not !

### Logs or Screenshots: (optional)
![image](https://user-images.githubusercontent.com/4571571/107263481-098f0900-6a57-11eb-84b2-3deba42f0c87.jpeg)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Windows     |  10 19H2 |
| apple cursor. | 1.1.0 |

**Comment by ful1e5** [comment]
Thanks, @iamr8 for the reporting.
It will be fixed soon. Check the other cursor has the same issue. So, I could **patch** altogether in the upcoming version.

**Comment by deckyazmi** [comment]
faced the same problem on linux.
![Screenshot from 2021-02-09 15-21-25](https://user-images.githubusercontent.com/28747076/107336031-3db40980-6aeb-11eb-81a2-b4785725da63.png)
