### ISSUE TITLE
Corner resize cursors are inverted

### ISSUE THREAD

**Issue by nstepien** [ful1e5/apple_cursor#39]
## Description of the problem
The cursors for corner resizing are inverted. Vertical/horizontal cursors are fine though.

### Logs or Screenshots: (optional)
![image](https://user-images.githubusercontent.com/567105/107877781-5dba4300-6ec6-11eb-978c-889937174883.png)
![image](https://user-images.githubusercontent.com/567105/107877790-63178d80-6ec6-11eb-8682-707c399f944a.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System |     win10         |

**Comment by ful1e5** [comment]
@nstepien Sorry for the misalignment.
I **altered** the Diagonals cursors in the source, So hope this **patch** works fixes this issue. Give **[this](https://filebin.net/7beae0yv1f2bnsag)** package a try.

**Comment by nstepien** [comment]
Works fine with the patch 👍
