### ISSUE TITLE
The windows release doesn't support HiDPI.

### ISSUE THREAD

**Issue by meowlgm** [ful1e5/apple_cursor#43]

**Comment by ful1e5** [comment]
Check the windows custom build [docs](https://github.com/ful1e5/apple_cursor#customize-windows-cursor-size)

**Comment by apfsx** [comment]
> 
> 
> Check the windows custom build [docs](https://github.com/ful1e5/apple_cursor#customize-windows-cursor-size)

Can you please explain this more? Windows hidpi does not work, I can seem to get only 1 or 2 cursors to be hi dpi but it doesn't seem they all do support hidpi. see screenshot.

<img width="413" alt="Screenshot_19" src="https://user-images.githubusercontent.com/57725572/112381674-d9bf5c00-8cb8-11eb-99a5-805b0bf452df.png">

**Comment by JforJason101** [comment]
The windows quality is so low

**Comment by ful1e5** [comment]
I Patched this bug inside **[dev](https://github.com/ful1e5/apple_cursor/tree/dev)** branch. Give it try 🙂.

### Workaround
```bash
# Make sure, you are up to date
$ git checkout dev
$ git pull

# Building only windows with one size that's "96". You can change it with the custom one. 
$ make windows WIN_SIZE=96
```

### Previews (Build with `WIN_SIZE=96`)
![mac OS Big Sur Cursors with HiDPi](https://i.imgur.com/7MTZJpq.png)

### Cursor Information
![mac OS Big Sur Cursors HiDPi Info](https://imgur.com/BDdSkX7.png)

**Comment by iamr8** [comment]
Hi @ful1e5. Just a question! Do you use windows? If yes, can you please say what is your theme engine ? Thanks in advance

**Comment by ful1e5** [comment]
@iamr8 **No**, I'm not a Windows user. I'm using Linux as a daily driver for about a half-decade. I **Haven't tried** any theme engine inside Windows back in the days.

**Comment by iamr8** [comment]
Ow thank you very much. I've asked that question because i though your OS-style is very similar to windows.

**Comment by JforJason101** [comment]
> I Patched this bug inside **[dev](https://github.com/ful1e5/apple_cursor/tree/dev?rgh-link-date=2021-03-31T11%3A53%3A12Z)** branch. Give it try 🙂.
> 
> ### Workaround
> ```shell
> # Make sure, you are up to date
> $ git checkout dev
> $ git pull
> 
> # Building only windows with one size that's "96". You can change it with the custom one. 
> $ make windows WIN_SIZE=96
> ```
> 
> ### Previews (Build with `WIN_SIZE=96`)
> ![mac OS Big Sur Cursors with HiDPi](https://camo.githubusercontent.com/854ef8381093eb9668e8cdd4047d81277e2b3f7928bc613153a0f3c4dd735b4a/68747470733a2f2f692e696d6775722e636f6d2f374d545a4a70712e706e67)
> 
> ### Cursor Information
> ![mac OS Big Sur Cursors HiDPi Info](https://camo.githubusercontent.com/6e73d13aeadc22f9e8304a19a42b26a4d968c6e13ebd2b771a616bb885bb2433/68747470733a2f2f696d6775722e636f6d2f424464536b58372e706e67)

Wait how do you install this tho?

**Comment by ful1e5** [comment]
@JforJason101 I can't install it on Linux System but there is **snap app** for testing _.cur_ & _.ani_ called [AniTuner](https://snapcraft.io/anituner). 
If you are using Windows you can install it by double click on `install.inf`,  Which was generated by the builder inside `<repo_path>/themes/macOSBigSur_Windows/`

**Comment by JforJason101** [comment]
there isn't an install.inf

**Comment by ful1e5** [comment]
> there isn't an install.inf

First, You have to run `make windows` inside the **project directory** for generating Windows Cursors.

**Comment by JforJason101** [comment]
bruh I'm sorry for being a pain in the butt, but this stuff is hard to install.

**Comment by apfsx** [comment]
I don't think its fixed yet,

@JforJason101 can you check this link for the latest release where @ful1e5 said he fixed it? It's still not showing hidpi for me.

https://github.com/ful1e5/apple_cursor/releases/tag/v1.1.4

**Comment by meowlgm** [comment]
Why the Windows cursor looks so big，the size is 48px，my monitor resolution is 4K, scaled to 150%，I have another macos cursor theme from a windows theme site, the size is 64px, it looks normal：
<img width="1581" alt="big" src="https://user-images.githubusercontent.com/81202884/114561546-3a322f80-9ca0-11eb-82bc-1b344af48d71.png">
<img width="1581" alt="small" src="https://user-images.githubusercontent.com/81202884/114561888-94cb8b80-9ca0-11eb-9253-1d8f07c1b664.png">

**Comment by apfsx** [comment]
> 
> 
> Why the Windows cursor looks so big，the size is 48px，my monitor resolution is 4K, scaled to 150%，I have another macos cursor theme from a windows theme site, the size is 64px, it looks normal：

Which release are you using? Your cursors look hidpi enabled. Do you have zip of installation you can upload?

**Comment by meowlgm** [comment]
> > Why the Windows cursor looks so big，the size is 48px，my monitor resolution is 4K, scaled to 150%，I have another macos cursor theme from a windows theme site, the size is 64px, it looks normal：
> 
> Which release are you using? Your cursors look hidpi enabled. Do you have zip of installation you can upload?

I builded it myself under ubuntu.

[macOSBigSur_Windows.zip](https://github.com/ful1e5/apple_cursor/files/6314727/macOSBigSur_Windows.zip)

**Comment by apfsx** [comment]
> 
> 
> > > Why the Windows cursor looks so big，the size is 48px，my monitor resolution is 4K, scaled to 150%，I have another macos cursor theme from a windows theme site, the size is 64px, it looks normal：
> > 
> > 
> > Which release are you using? Your cursors look hidpi enabled. Do you have zip of installation you can upload?
> 
> I builded it myself under ubuntu.
> 
> [macOSBigSur_Windows.zip](https://github.com/ful1e5/apple_cursor/files/6314727/macOSBigSur_Windows.zip)

I am running 4k too and I think it has to do something with Windows.

For example, in Control Panel > Mouse select theme "None" or Windows Classic. The cursor on my screen is also same size as the zip size you provided. Why? I don't know.
