### ISSUE TITLE
Restore sharp-tailed cursors as separate packages

### ISSUE THREAD

**Issue by juujuujj** [ful1e5/apple_cursor#66]
I like the new more faithful update to the cursor, but the fact it also changed for sizes other than 24 makes it less faithful when taken into account when testing the sizes excluding 24. As a compensation, you can offer the current version of the cursors with the sharp tail in separate packages

**Comment by ful1e5** [comment]
Can your issue be solved with the macOS Monterney cursor? These cursors had sharp tails.

**Comment by doncsugar** [comment]
I think it's unavoidable. Apple is definitely using to custom assets for each resolution. There should probably be a separate svg for the <=24px resolutions and the original square one should be used for the higher resolutions.

**Comment by farhadh** [comment]
> Can your issue be solved with the macOS Monterney cursor? These cursors had sharp tails.

Yes, it will. I use macOS Monterey and it has sharp tails :)
