### ISSUE TITLE
Text cursor state

### ISSUE THREAD

**Issue by Tedium16** [ful1e5/apple_cursor#67]
The state the cursor acquires whenever it hovers over text, used to be nicely sized, it became a bit bigger than the cursor in its original state, but this allowed it to still look not to blurry at size 24. However, since your cursor size update, that rectified the issue mentioned in issue #64, however now it has caused (in my opinion) the text state to be a bit too small, and be harder than before to see the details
 I don't make cursor themes so I don't know if you can individually edit the sizes of states relative to their counterparts, but I just thought that I should inform you of this.

**Comment by ful1e5** [comment]
Check [build #188](https://github.com/ful1e5/apple_cursor/actions/runs/1475678669) for binaries.

**Comment by Tedium16** [comment]
Thx for listening, its better now.
