### ISSUE TITLE
Increasing Font Size of the cursors

### ISSUE THREAD

**Issue by Amrut2** [ful1e5/apple_cursor#68]
## Description of the problem

How can I increase the font size of the cursor in windows 11 ? that's the only problem I am facing.

## How has this issue affected you? What are you trying to accomplish?
 

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System |      windows 11        |

**Comment by SunnyMonster123** [comment]
I'm also having the same problem on Windows 11.

**Comment by Void48** [comment]
125% scaling@1440p. cursor is small :/

**Comment by neerajhk** [comment]
So at 1080p on Windows 11 it looks blurry. Anything I can try to fix this? I don't have experience with cursor coding, let me know if I can provide something that can help. Thanks.

**Comment by niphoneua** [comment]
Maybe this will help
