### ISSUE TITLE
Uninstalling of Cursor

### ISSUE THREAD

**Issue by smit-sms** [ful1e5/apple_cursor#79]
## Description of the problem
Please include guide/steps to Uninstall the Cursor
## How has this issue affected you? What are you trying to accomplish?
Unable to uninstall cursor. Wanted to remove the current cursor and install new one, but the steps for uninstalling the cursor cannot be found anywhere online. Moreover, there is no "uninstall" file available for the same. It would be nice to include the steps if not the file to uninstall the cursor.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System | Windows 10 |

**Comment by ful1e5** [comment]
I'm **not** a Windows user. But anyone out there is able to write documentation/script for uninstalling windows cursor, your contribution is appreciated.

**Comment by smit-sms** [comment]
I can take this issue up, if that's okay? Please assign it to me. Will work on documenting the same with a detailed walkthrough steps. @ful1e5

**Comment by smit-sms** [comment]
If you permit, I have also written a 'batch' script to delete the registry key entry for a normal user. I have also converted the script into an executable i.e. "uninstall.exe" that could potentially ease the user's uninstallation procedure. Let me know if interested, we can work it out. @ful1e5

**Comment by ful1e5** [comment]
batch script sounds good.

**Comment by smit-sms** [comment]
Please go through the zipped batch file attached. If all good, then let's look forward to merge with the current assets.

[uninstall.zip](https://github.com/ful1e5/apple_cursor/files/7939533/uninstall.zip)
