### ISSUE TITLE
Change cursor theme when "windows theme" changes(automatically).

### ISSUE THREAD

**Issue by ghost** [ful1e5/apple_cursor#89]
# What is this feature? 
Change cursor theme when "windows theme" changes(automatically).
# How the feature should work?
windows changes to dark mode(there is alot of application that does this). cursor changes it's theme from light to dark for example
# You have examples or an idea of how it can be implemented?

**Comment by artchsh** [comment]
As i know, there is no function in windows to do it. It could be added by using some kind of script, to change the cursor when windows mode changed. Try to google that kind of script, and then adjust it's settings to this cursor. But i think that's not author's responsibility.

**Comment by artchsh** [comment]
There is no function in Windows that allows you to do it. You can achieve this using third-party programs to create a script, that changes the cursor when Windows theme mode changes. 
Vanilla windows do not support that.
