### ISSUE TITLE
Arch/AUR installer

### ISSUE THREAD

**Issue by VDuchauffour** [ful1e5/apple_cursor#91]
Hello,
Thank you for your work on this project. 
I would know if it could be possible to create a package for Arch (on `AUR` for instance) ?
Thanks.

**Comment by ful1e5** [comment]
There is already [AUR](https://aur.archlinux.org/packages/apple_cursor) available. I will add the AUR installation in README.md soon.

**Comment by VDuchauffour** [comment]
Ok thanks!
