### ISSUE TITLE
Real Monterey and Big Sur cursors

### ISSUE THREAD

**Issue by qo4on** [ful1e5/apple_cursor#95]
Your cursors don't look like the real Monterey and Big Sur cursors:

https://support.apple.com/en-za/guide/mac-help/mh35695/12.0/mac/12.0
https://support.apple.com/en-za/guide/mac-help/mh35695/11.0/mac/11.0

**Comment by artchsh** [comment]
I think that's because the author tried to optimize these for Windows either finding .PNG files and then creating a script for installing and building them.

**Comment by ful1e5** [comment]
@qo4on The official presentation of Apple's website showcasing cursors does not represent the actual cursor used inside macOS. The Apple website provides very little information about cursor states and their images. 

If anyone in the community has macOS and can share all the states, I would like to investigate and ensure that this cursor matches the exact appearance of the macOS cursor.

**Comment by AnirudhMemani** [comment]
Why does the latest version make my cursors look huge on windows? Also, the Link cursor shows the wrong cursor and the waiting cursor is much smaller compared to other cursors.
